package com.filip.tecajnalistahnb.common

const val AUSTRALIA = "AUD"
const val CANADA = "CAD"
const val CZECH_REPUBLIC = "CZK"
const val DENMARK = "DKK"
const val HUNGARY = "HUF"
const val JAPAN = "JPY"
const val NORWAY = "NOK"
const val SWEDEN = "SEK"
const val SWITZERLAND = "CHF"
const val UNITED_KINGDOM = "GBP"
const val USA = "USD"
const val BOSNIA_AND_HERZEGOVINA = "BAM"
const val EMU = "EUR"
const val POLAND = "PLN"